#!/usr/bin/env python3
import json

URL = "https://mammothmurals.com/"

tokens = {
    "ease.signature": {
        "bezier": "cubic-bezier(0.31, 0.75, 0.22, 1)",
        "gsap": "approx power2.out / back-ish",
        "note": "House ease. Buttons, CTA arrows, accordion, nav. Slight overshoot-free fast-out.",
        "usedBy": ["3d-text-roll-button", "services-cta-arrow", "accordion-expand"],
    },
    "ease.smooth": {
        "bezier": "cubic-bezier(0.16, 1, 0.3, 1)",
        "gsap": "expo.out",
        "note": "Strong decelerating ease. Work-card image settle, work clip transitions.",
        "usedBy": ["work-card-image-zoom"],
    },
    "ease.inOut": {
        "bezier": "cubic-bezier(0.625, 0.05, 0, 1)",
        "gsap": "approx power3.inOut / quint.inOut",
        "note": "Accordion icon rotate, vimeo-lightbox close.",
        "usedBy": ["accordion-expand", "vimeo-lightbox"],
    },
    "dur.fast": "0.45s",
    "dur.smooth": "0.65s",
    "dur.reveal": "~0.94s (measured, per line)",
    "sprite.spriteFrames": {"timing": "steps(4)", "duration": "0.5s", "frames": 4, "fps": 8},
    "sprite.wiggle": {"timing": "steps(2)", "duration": "0.23s"},
}

patterns = [
    {
        "id": "p-3d-text-roll-button",
        "trigger": "hover",
        "appliesTo": ".g_btn_main / .navbar_btn_default (x many buttons sitewide)",
        "summary": "Two-layer button label. On hover the front label scales to 0 while a back duplicate, parked folded-back in 3D (rotateX/Y/Z + y/x offset), unfolds to identity. A 3D flip text swap.",
        "confidence": "_approx3d",
    },
    {
        "id": "p-char-roll-link",
        "trigger": "hover",
        "appliesTo": "nav links (.navbar_home_link_contain), inline/footer links (.g_link_text), menu links (.menu_links_link)",
        "summary": "SplitText per-character roll: each char translates up by ~1 line-height (a duplicate rolls in from below), staggered ~14-22ms across the word. GSAP-driven, easing not readable from computed style.",
        "confidence": "unknown — verify",
    },
    {
        "id": "p-sprite-loop",
        "trigger": "load",
        "appliesTo": ".u-sprite decorations (smiley, nge, hero deco/play-btn, work stop, testimonials backquote, contact, footer) (x10)",
        "summary": "CSS sprite-sheet loop: background-position stepped through 4 frames at ~8fps, infinite (animation spriteFrames 0.5s steps(4)). A separate 'wiggle' steps(2) 0.23s drives the page-transition text.",
        "confidence": "measured",
    },
    {
        "id": "p-scrub-parallax",
        "trigger": "scroll",
        "appliesTo": "hero image, work header, section overlaps (x4 GSAP ScrollTrigger scrub tweens)",
        "summary": "Scroll-scrubbed parallax (ease:none, linear to scroll). Foreground/background layers translate at different rates; sections overlap by sliding yPercent as the next section enters.",
        "confidence": "measured",
    },
]

animations = [
    # ---------------- SIGNATURE ----------------
    {
        "id": "hero-line-reveal",
        "label": "Hero headline + paragraph line-mask reveal (load)",
        "selector": "h1.hero_home_heading / p.hero_home_p (.lines-split inside .lines-split-mask)",
        "trigger": "load",
        "mechanism": "splittext (line-mask, translateY)",
        "patternId": None,
        "layers": 24,
        "stagger": {"items": 23, "ms": 164, "note": "avg across both blocks; per-block stagger is finer/noisy"},
        "lead": {
            "selector": "div.lines-split (one line)",
            "from": {"transform": "translateY(166px)"},
            "to": {"transform": "translateY(0)"},
            "duration": "~0.94s",
            "ease": "(GSAP — measured profile is a heavy ease-out, ~expo.out)",
            "easeBezier": "approx cubic-bezier(0.16, 1, 0.3, 1)",
        },
        "confidence": "unknown — verify",
        "timelineRef": "timelines/hero-load-reveal.json",
        "notes": "Captured live by reloading and arming __cap.scan(trigger:manual) ~382ms into load (a page-transition loader buys the window). Each text line sits one line-height (~166px) below, clipped by an overflow:hidden mask, and slides up. Measured deceleration: 166>123>88>48>26>17>9>2.6>0 over 937ms = strong ease-out. Per-line stagger present; exact value and easing are GSAP/rAF so not exactly readable.",
    },
    {
        "id": "3d-text-roll-button",
        "label": "Primary + nav button 3D text-roll on hover",
        "selector": "a.g_btn_main / a.navbar_btn_default (.g_btn_container + .is-duplicate)",
        "trigger": "hover",
        "mechanism": "transform (scale + 3D rotate)",
        "patternId": "p-3d-text-roll-button",
        "layers": 2,
        "stagger": None,
        "lead": {
            "selector": "div.g_btn_container.is-duplicate (back label)",
            "from": {"transform": "translate3d(-6.9px,37.4px,24px) rotateX(34.4deg) rotateY(19.1deg) rotateZ(23.1deg)", "_note": "front label .g_btn_container goes scale 1 -> 0 simultaneously"},
            "to": {"transform": "none (identity)"},
            "duration": "0.45s",
            "ease": "ease.signature",
            "easeBezier": "cubic-bezier(0.31, 0.75, 0.22, 1)",
        },
        "confidence": "_approx3d",
        "timelineRef": "timelines/primary-button-hover.json",
        "notes": "Two captures agree (g_btn_main + navbar_btn_default share the mechanism). Front .g_btn_container scales 1->0; back .is-duplicate unfolds from a folded-back 3D pose to identity. Translate/scale exact; rotation decomposed from matrix3d (approximate). Navbar variant: y 44->0, rotateX -34.4, rotateY -19.1, rotateZ 23.1.",
    },
    {
        "id": "work-card-image-zoom",
        "label": "Work card image tiles settle-zoom on hover",
        "selector": "a.work_home_item_link (.work_home_cover_deco tiles)",
        "trigger": "hover",
        "mechanism": "transform (scale)",
        "patternId": None,
        "layers": 6,
        "stagger": {"items": 5, "ms": 129},
        "lead": {
            "selector": "div.work_home_cover_deco",
            "from": {"transform": "scale(1.1)"},
            "to": {"transform": "scale(1.0)"},
            "duration": "0.65s",
            "ease": "ease.smooth",
            "easeBezier": "cubic-bezier(0.16, 1, 0.3, 1)",
        },
        "confidence": "measured",
        "timelineRef": "timelines/work-card-hover.json",
        "notes": "Image tiles rest at scale 1.1 (slightly zoomed) and settle to 1.0 on hover, ~129ms staggered across ~5 tiles. CSS-transition driven (duration/ease read from computed style). The .work_home_link_clip (clip-path) and .work_home_link_overlay (opacity) carry CSS transition decls (0.65s / 0.45s) but showed NO motion on hover at this viewport (see work-card-clip.json / work-card-overlay.json, both moved:0).",
    },
    {
        "id": "cta-wheel-scale-in",
        "label": "Final CTA image wheel staggered scale-in (scroll)",
        "selector": "div.g_cta_collection (.g_cta_image x7) — ScrollTrigger[3] onEnter",
        "trigger": "scroll",
        "mechanism": "transform (scale)",
        "patternId": None,
        "layers": 7,
        "stagger": {"items": 7, "ms": 58},
        "lead": {
            "selector": "div.g_cta_image",
            "from": {"transform": "scale(1.185)", "_static": "rotate(15deg) translate(-36px,-108px) held constant — that is the wheel layout, not animated"},
            "to": {"transform": "scale(1.0)"},
            "duration": "~0.65s",
            "ease": "(GSAP — easing not readable)",
            "easeBezier": None,
        },
        "confidence": "unknown — verify",
        "timelineRef": "timelines/cta-wheel-reveal.json",
        "notes": "7 images arranged in a wheel (each pre-rotated ~15deg and offset) pop in by scaling 1.185 -> 1.0, ~58ms apart, as the collection enters view (GSAP ScrollTrigger onEnter callback, not a scrub tween). Only scale animates; rotate/translate are the static wheel positions.",
    },
    {
        "id": "wordmark-scroll-drift",
        "label": "Wordmark inertia drift on scroll velocity",
        "selector": "a.navbar_home_link_wordmark — ScrollTrigger[6] (trigger:null, onUpdate, start 'top -300' end 'max')",
        "trigger": "scroll",
        "mechanism": "transform (translateX driven by scroll velocity + tiny skew)",
        "patternId": None,
        "layers": 5,
        "stagger": None,
        "lead": {
            "selector": "a.navbar_home_link_wordmark",
            "from": {"transform": "translateX(0)"},
            "to": {"transform": "translateX(up to ~-235px) then eases back to 0 when scrolling stops"},
            "duration": "~0.65s settle-back",
            "ease": "(GSAP onUpdate — velocity mapped, not fixed)",
            "easeBezier": None,
        },
        "confidence": "unknown — verify",
        "timelineRef": "timelines/wordmark-scroll-drift.json",
        "notes": "Verified scroll-velocity-reactive, NOT a fixed marquee: idle x returns to 0 (read 0 after 1.5s no scroll), a +400px scroll snapped x to -235px. A ~0.001deg skew rides along. Magnitude depends on scroll speed. This is the only behavior of ScrollTrigger[6]'s onUpdate.",
    },
    {
        "id": "work-cover-crossfade",
        "label": "Work-cover image crossfade (scroll-gated)",
        "selector": "div.work_home_cover (img.work_home_image x N) — ScrollTrigger[7] onEnter/onLeave",
        "trigger": "scroll",
        "mechanism": "opacity",
        "patternId": None,
        "layers": 2,
        "stagger": None,
        "lead": {
            "selector": "img.work_home_image.u-ratio-3-2",
            "from": {"opacity": 1},
            "to": {"opacity": 0, "_paired": "a sibling image goes 0 -> 1 simultaneously (crossfade)"},
            "duration": "~0.3s",
            "ease": "(GSAP — not readable)",
            "easeBezier": None,
        },
        "confidence": "unknown — verify",
        "timelineRef": "timelines/work-cover-reveal.json",
        "notes": "An image crossfade slideshow inside the work cover; one image fades out while the next fades in (~0.3s). ScrollTrigger[7] onEnter/onLeave/onEnterBack/onLeaveBack play/pause it by visibility.",
    },

    # ---------------- PATTERN INSTANCES ----------------
    {
        "id": "nav-link-char-roll",
        "label": "Nav link per-character roll-up on hover",
        "selector": "div.navbar_home_link_contain (.stagger-char x13)",
        "trigger": "hover",
        "mechanism": "splittext (per-char translateY)",
        "patternId": "p-char-roll-link",
        "layers": 13,
        "stagger": {"items": 13, "ms": 14},
        "lead": {
            "selector": "div.stagger-char",
            "from": {"transform": "translateY(0)"},
            "to": {"transform": "translateY(-31.1px)"},
            "duration": "~0.40s",
            "ease": "(GSAP — not readable)",
            "easeBezier": None,
        },
        "confidence": "unknown — verify",
        "timelineRef": "timelines/navbar-link-hover.json",
        "notes": "Each character rolls up by ~31px (one line-height) with a duplicate rolling in; ~14ms stagger across 13 chars.",
    },
    {
        "id": "footer-link-char-roll",
        "label": "Inline/footer link per-character roll-up on hover",
        "selector": "a.g_link_text (.stagger-char)",
        "trigger": "hover",
        "mechanism": "splittext (per-char translateY)",
        "patternId": "p-char-roll-link",
        "layers": 4,
        "stagger": {"items": 4, "ms": 22},
        "lead": {
            "selector": "div.stagger-char",
            "from": {"transform": "translateY(0)"},
            "to": {"transform": "translateY(-60px)"},
            "duration": "~0.38s",
            "ease": "(GSAP — not readable)",
            "easeBezier": None,
        },
        "confidence": "unknown — verify",
        "timelineRef": "timelines/generic-link-hover.json",
        "notes": "Same char-roll mechanism as nav links; larger glyphs so the roll distance is ~60px. ~22ms stagger.",
    },
    {
        "id": "sprite-loops",
        "label": "Sprite-sheet decoration loops",
        "selector": ".u-sprite (e.g. div.hero_home_deco, transition_smiley, transition_nge, work_home_inner_stop, testimonials_heading_backquote, footer_bottom_deco_wrap)",
        "trigger": "load",
        "mechanism": "backgroundPosition (stepped sprite)",
        "patternId": "p-sprite-loop",
        "layers": 10,
        "stagger": None,
        "lead": {
            "selector": "div.hero_home_deco.u-sprite (sampled instance: play-button sprite)",
            "from": {"backgroundPosition": "0px 0px"},
            "to": {"backgroundPosition": "cycles -717px / -1075.5px / 0px / -358.5px"},
            "duration": "0.5s loop (steps(4), ~8fps)",
            "ease": "steps(4)",
            "easeBezier": "steps(4)",
            "spriteSheet": "https://cdn.prod.website-files.com/6870db6428fa0046e4e9dc88/68a84f74a437cee3c4b0d99c_playbtn.avif",
            "backgroundSize": "1434px 361px (4 frames of 358.5px)",
        },
        "confidence": "measured",
        "timelineRef": "timelines/sprite-loop.json",
        "notes": "All .u-sprite share animation 'spriteFrames' 0.5s steps(4) infinite (4 frames @ ~8fps). Each element points at its own AVIF sheet (sampled: playbtn). Page-transition text uses a separate 'wiggle' steps(2) 0.23s loop.",
    },

    # ---------------- POLISH ----------------
    {
        "id": "services-cta-arrow",
        "label": "Services CTA arrow nudge on hover",
        "selector": "a.services_home_cta (.services_home_cta_arrow + text)",
        "trigger": "hover",
        "mechanism": "transform (translateX)",
        "patternId": None,
        "layers": 6,
        "stagger": {"items": 4, "ms": 0, "note": "simultaneous"},
        "lead": {
            "selector": "div.services_home_cta_arrow.u-text-style-display",
            "from": {"transform": "translateX(-11.5px)"},
            "to": {"transform": "translateX(0)"},
            "duration": "0.45s",
            "ease": "ease.signature",
            "easeBezier": "cubic-bezier(0.31, 0.75, 0.22, 1)",
        },
        "confidence": "measured",
        "timelineRef": "timelines/services-cta-arrow-hover.json",
        "notes": "Arrow + label slide right ~11.5px on hover (CSS transition; duration/ease from computed style).",
    },
    {
        "id": "accordion-expand",
        "label": "FAQ accordion expand/collapse on click",
        "selector": "div.g_faq_item — click button.accordion_css_item_top",
        "trigger": "click",
        "mechanism": "height + transform + opacity (+ icon rotate)",
        "patternId": None,
        "layers": 7,
        "stagger": None,
        "lead": {
            "selector": "div.accordion_css_item_bottom / .accordion_css_bottom_wrap (content)",
            "from": {"height": "0px", "overflow": "hidden", "_state": ".accordion_css_state at translateX(10px) opacity 0; icon at rest"},
            "to": {"height": "auto (~78px content)", "_state": ".accordion_css_state to translateX(0) opacity 1; icon rotates"},
            "duration": "0.5s (state) / 0.75s (contain) / 0.6s (icon)",
            "ease": "ease.signature",
            "easeBezier": "cubic-bezier(0.31, 0.75, 0.22, 1)",
        },
        "confidence": "measured",
        "timelineRef": "timelines/accordion-expand.json",
        "notes": "Class-toggle accordion (no checkbox). On open: content wrapper height 0 -> content (overflow hidden), the open/close state label slides in (x 10->0) and fades (0->1) over 0.5s/0.25s, the +/- icon rotates (0.6s ease.inOut cubic-bezier(0.625,0.05,0,1)). Open/closed computed values read directly. Lead captured value was the state x-slide; height + icon read from open-vs-closed computed style.",
    },
    {
        "id": "vimeo-lightbox",
        "label": "Vimeo lightbox button + close (polish)",
        "selector": "div.vimeo-lightbox__btn / button.vimeo-lightbox__close",
        "trigger": "hover",
        "mechanism": "opacity / all",
        "patternId": None,
        "layers": 2,
        "stagger": None,
        "lead": {
            "selector": "div.vimeo-lightbox__btn",
            "from": {"opacity": "rest"},
            "to": {"opacity": "hover"},
            "duration": "0.3s (btn) / 0.5s (close)",
            "ease": "linear (btn) / ease.inOut (close)",
            "easeBezier": "linear / cubic-bezier(0.625, 0.05, 0, 1)",
        },
        "confidence": "measured",
        "timelineRef": None,
        "notes": "Read from CSS transition declarations only (map cssHovers); the lightbox modal itself was not opened/captured. btn opacity 0.3s linear; close 'all' 0.5s cubic-bezier(0.625,0.05,0,1).",
    },

    # ---------------- MEASURED FROM REGISTRY (scrub parallax) ----------------
    {
        "id": "hero-image-parallax",
        "label": "Hero image scroll parallax",
        "selector": "img.hero_home_image.u-ratio-16-9 — ScrollTrigger[1] scrub",
        "trigger": "scroll",
        "mechanism": "transform (translateY, scrubbed)",
        "patternId": "p-scrub-parallax",
        "layers": 1,
        "stagger": None,
        "lead": {
            "selector": "img.hero_home_image.u-ratio-16-9",
            "from": {"transform": "translateY(0)"},
            "to": {"transform": "translateY(125px)"},
            "duration": "scrubbed (start 'top bottom' -> end 'bottom top')",
            "ease": "none (linear to scroll)",
            "easeBezier": "linear",
        },
        "confidence": "measured",
        "timelineRef": None,
        "notes": "Read directly from the GSAP ScrollTrigger registry (bound tween: y 0->125, ease none, scrub true). No capture needed.",
    },
    {
        "id": "work-header-parallax",
        "label": "Work header counter-parallax",
        "selector": "div.work_home_inner — ScrollTrigger[2] scrub",
        "trigger": "scroll",
        "mechanism": "transform (translateY, scrubbed)",
        "patternId": "p-scrub-parallax",
        "layers": 1,
        "stagger": None,
        "lead": {
            "selector": "div.work_home_inner",
            "from": {"transform": "translateY(0)"},
            "to": {"transform": "translateY(-125px)"},
            "duration": "scrubbed",
            "ease": "none (linear to scroll)",
            "easeBezier": "linear",
        },
        "confidence": "measured",
        "timelineRef": None,
        "notes": "Registry bound tween: y 0->-125, ease none, scrub. Moves opposite the hero image for depth.",
    },
    {
        "id": "section-overlap-parallax",
        "label": "Section overlap (next section slides over previous)",
        "selector": "section.work_home_wrap & section.services_home_wrap — ScrollTrigger[4] & [5] scrub",
        "trigger": "scroll",
        "mechanism": "transform (translateYPercent, scrubbed)",
        "patternId": "p-scrub-parallax",
        "layers": 2,
        "stagger": None,
        "lead": {
            "selector": "section.work_home_wrap",
            "from": {"transform": "translateY(0%)"},
            "to": {"transform": "translateY(20%)"},
            "duration": "scrubbed (start 'top bottom' -> end 'top top')",
            "ease": "none (linear to scroll)",
            "easeBezier": "linear",
        },
        "confidence": "measured",
        "timelineRef": None,
        "notes": "Two registry scrub tweens: as services_home_wrap enters, work_home_wrap moves yPercent 20 (ST4); as about_home_wrap enters, services_home_wrap moves yPercent 20 (ST5). Creates a layered overlap/cover-up reveal between sections.",
    },
    {
        "id": "partners-logo-drift",
        "label": "Partners logo vertical drift/cycle on enter",
        "selector": "div.partners_home_wrap (.partners_logo_target) — ScrollTrigger[0] onEnter/onLeave",
        "trigger": "scroll",
        "mechanism": "transform (translateY)",
        "patternId": None,
        "layers": 2,
        "stagger": None,
        "lead": {
            "selector": "div.partners_logo_target",
            "from": {"transform": "translateY(0)"},
            "to": {"transform": "translateY(~-25px)"},
            "duration": "~3.5s",
            "ease": "(GSAP — not readable)",
            "easeBezier": None,
        },
        "confidence": "unknown — verify",
        "timelineRef": "timelines/partners-marquee.json",
        "notes": "Logo target columns drift up ~21-25px over ~3.5s when the partners section enters; ScrollTrigger[0] play/pauses it by visibility (onEnter/onLeave/onEnterBack/onLeaveBack). Slow drift/cycle, GSAP-driven, easing not readable. Likely a logo carousel cycle.",
    },
]

unspecced = [
    {"id": "page-transition-overlay", "note": "Brand page-transition/preloader overlay (transition_text 'wiggle' steps(2) 0.23s + transition_smiley / transition_nge sprite characters spriteFrames steps(4) 0.5s). Fires on navigation/initial load before the app is interactive; mechanism is known from CSS loops but the timed in/out of the overlay itself was not captured. The hero-line-reveal was caught just after it."},
    {"id": "hero-video / vimeo-lightbox-modal", "note": "Hero has a play button (sprite) opening a Vimeo lightbox modal. Modal open/close transitions read from CSS only (see vimeo-lightbox); modal content not opened/captured (external embed)."},
    {"id": "menu-open (mobile)", "note": "Fullscreen menu (.menu_links, .navbar_menu_btn) is display:none at 1280px (mobile-only hamburger). Its char-stagger link reveals (.menu_links_text x28) follow p-char-roll-link. Not triggerable at desktop viewport; not captured."},
    {"id": "work-card-clip/overlay", "note": ".work_home_link_clip (clip-path inset, 0.65s) and .work_home_link_overlay (opacity, 0.45s) have CSS transition declarations but produced no measured motion on hover at 1280px (both captures moved:0). Either gated by a state we did not reach or visually negligible. Worth verifying."},
]

doc = {
    "meta": {
        "url": URL,
        "capturedAt": "2026-06-15",
        "viewport": [1280, 800],
        "stack": ["GSAP", "ScrollTrigger", "Lenis", "Webflow", "jQuery"],
        "method": "agent-browser (one headed Chromium session) + window.__cap capture engine (extension/capture-animation.js) injected via --init-script. Phase 1 __cap.map() static registry/CSS read; Phase 2 __cap.scan()/on() live per-frame computed-style diff while driving real hover/scroll/click by selector.",
        "notes": "Webflow + GSAP build with Lenis smooth-scroll. Scrub parallax + sprite loops read from registry/CSS (measured). Hover/click/reveal motion captured live in a visible tab (headless does not advance these). GSAP-driven reveals report duration but not easing (computed style can't expose GSAP eases) -> 'unknown — verify'. 3D button rotation decomposed from matrix3d -> '_approx3d'.",
    },
    "tokens": tokens,
    "patterns": patterns,
    "animations": animations,
    "unspecced": unspecced,
}

json.dump(doc, open("animations.json", "w"), indent=2)
print("wrote animations.json:", len(animations), "animations,", len(patterns), "patterns,", len(unspecced), "unspecced")
# integrity: every timelineRef exists
import os
missing = [a["timelineRef"] for a in animations if a.get("timelineRef") and not os.path.exists(a["timelineRef"])]
print("missing timeline files:", missing or "none")
